% =========================================================================
% >> Linked/Coulped Stress Release Model (LSRM) Script
% A marked point process in time-stress space with the conditional 
% intensity function
% Modified at: Yu. 2026/03/25
% =========================================================================
% In the univariate stress release model (SRM), the regional stress level
% X(t) increases deterministically between two earthquakes and releases
% stochastically as a scalar Markov process;
% However, LSRM takes into account interactions among different subregions
% due to stress transfer, reflected by the parameter θ
% =========================================================================
% θij measures the ﬁxed proportion of stress drop from events, initiated in
% the subregion j, which is transferred to the subregion i;
% In the simpler parameterisation: Cij>0 means damping (j to i) and
% Cij<0 means excitation (j to i); Cij=0 means no interaction between them;
% and if C=ones(Nregion), it means stress transfer is equal both the region
% so that λ1=λ2;
% If assuming c12=c21,its physical meaning is that the interaction way in 
% two subregions and the corresponding time length of stress release (or
% increase) level caused by earthquakes in another subregion are identical
% =========================================================================
% Length of params=n^2+2n=n(n+2); Here suppose n=2: 
global evalNums
evalNums=200;
Nregion=2;
rng(2025);
% Data-components: [time,mag,reg,Mmin]
time=EventTime;
mag=EventMag;
reg=randi([1,Nregion],length(time),1); % randomly
Mmin=4;


%% Conditional intensity and Practise
A=[-2;-2];
B=[0.01;0.01];
C=0.5*ones(Nregion);
C(1,2)=-0.0;
C(2,1)=-0.0;
params=LSRM_PackingParam(A,B,C);
% AIC0=LSRM_AIC(time,mag,reg,params,Mmin);
LSRM_PlotResults(LSRM_Estimate(time,mag,reg,params,Mmin),reg,time,mag,Mmin);

%% MLE-Fitting
[pNew,AICNew]=LSRM_MLE(time,mag,reg,params,Mmin);

%% Plot-Fitting
LSRM_PlotResults(LSRM_Estimate(time,mag,reg,pNew,Mmin),reg,time,mag,Mmin);
% AIC=LSRM_AIC(time,mag,reg,pNew,Mmin);

%% RPP-analysis
[CumInt]=LSRM_Integral_Time(time,mag,reg,pNew,Mmin);
LSRM_RPP(CumInt,time,reg);

%% Or like this:
[CumInt]=LSRM_Integral_Region(time,mag,reg,pNew,Mmin);
LSRM_RPP_Transformed(CumInt,reg);

% We can also apply this model to the synthetic catalogues, especially to
% those generated by considering special tectonic regions or geophysical 
% mechanism (Mora and Place.1998) and improve simulation models for
% earthquake process


